const UPDATE_AILABILITY_UNKNOWN = 0;
const UPDATE_AILABILITY_NOT_AVAILABLE = 1;
const UPDATE_AILABILITY_AVAILABLE = 2;
const UPDATE_AILABILITY_IN_PROGRESS = 3;

const INSTALL_STATUS_UNKNOWN = 0;
const INSTALL_STATUS_DOWNLOADED = 1;
const INSTALL_STATUS_DOWNLOADING = 2;
const INSTALL_STATUS_FAILED = 3;
const INSTALL_STATUS_INSTALLING = 4;
const INSTALL_STATUS_PENDING = 5;

const ACTIVITY_RESULT_OK = -1;
const ACTIVITY_RESULT_CANCELED = 0;
const ACTIVITY_RESULT_NOT_FOUND = 2;

const UPDATE_ERROR_DOWNLOAD = 4002;
const UPDATE_ERROR_BLOCKED = 4003;
const UPDATE_ERROR_INVALID_APK = 4004;
const UPDATE_ERROR_CONFLICT = 4005;
const UPDATE_ERROR_STORAGE = 4006;
const UPDATE_ERROR_INCOMPATIBLE = 4007;
const UPDATE_ERROR_APP_NOT_OWNED = 4008;
const UPDATE_ERROR_INTERNAL_ERROR = 4009;
const UPDATE_ERROR_ABORTED = 4010;
const UPDATE_ERROR_APK_NOT_FOUND = 4011;
const UPDATE_ERROR_EXTERNAL_SOURCE_DENIED = 4012;
