const int UPDATE_AVAILABILITY_UNKNOWN = 0;
const int UPDATE_AVAILABILITY_NOT_AVAILABLE = 1;
const int UPDATE_AVAILABILITY_AVAILABLE = 2;
const int UPDATE_AVAILABILITY_IN_PROGRESS = 3;

@Deprecated('Use UPDATE_AVAILABILITY_UNKNOWN instead.')
const int UPDATE_AILABILITY_UNKNOWN = UPDATE_AVAILABILITY_UNKNOWN;
@Deprecated('Use UPDATE_AVAILABILITY_NOT_AVAILABLE instead.')
const int UPDATE_AILABILITY_NOT_AVAILABLE = UPDATE_AVAILABILITY_NOT_AVAILABLE;
@Deprecated('Use UPDATE_AVAILABILITY_AVAILABLE instead.')
const int UPDATE_AILABILITY_AVAILABLE = UPDATE_AVAILABILITY_AVAILABLE;
@Deprecated('Use UPDATE_AVAILABILITY_IN_PROGRESS instead.')
const int UPDATE_AILABILITY_IN_PROGRESS = UPDATE_AVAILABILITY_IN_PROGRESS;

const int INSTALL_STATUS_UNKNOWN = 0;
const int INSTALL_STATUS_DOWNLOADED = 1;
const int INSTALL_STATUS_DOWNLOADING = 2;
const int INSTALL_STATUS_FAILED = 3;
const int INSTALL_STATUS_INSTALLING = 4;
const int INSTALL_STATUS_PENDING = 5;

const int ACTIVITY_RESULT_OK = -1;
const int ACTIVITY_RESULT_CANCELED = 0;
const int ACTIVITY_RESULT_NOT_FOUND = 2;

const int UPDATE_ERROR_DOWNLOAD = 4002;
const int UPDATE_ERROR_BLOCKED = 4003;
const int UPDATE_ERROR_INVALID_APK = 4004;
const int UPDATE_ERROR_CONFLICT = 4005;
const int UPDATE_ERROR_STORAGE = 4006;
const int UPDATE_ERROR_INCOMPATIBLE = 4007;
const int UPDATE_ERROR_APP_NOT_OWNED = 4008;
const int UPDATE_ERROR_INTERNAL_ERROR = 4009;
const int UPDATE_ERROR_ABORTED = 4010;
const int UPDATE_ERROR_APK_NOT_FOUND = 4011;
const int UPDATE_ERROR_EXTERNAL_SOURCE_DENIED = 4012;
