const UPDATE_AILABILITY_UNKNOWN = 0;
const UPDATE_AILABILITY_NOT_AVAILABLE = 1;
const UPDATE_AILABILITY_AVAILABLE = 2;
const UPDATE_AILABILITY_IN_PROGRESS = 3;

const INSTALL_STATUS_UNKNOWN = 0;
const INSTALL_STATUS_DOWNLOADED = 1;
const INSTALL_STATUS_DOWNLOADING = 2;
const INSTALL_STATUS_FAILED = 3;
const INSTALL_STATUS_INSTALLING = 4;
const INSTALL_STATUS_PENDING = 5;
