// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package ru.rustore.flutter_rustore_update.pigeons;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Rustore {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class UpdateInfo {
    private @NonNull Long availableVersionCode;

    public @NonNull Long getAvailableVersionCode() {
      return availableVersionCode;
    }

    public void setAvailableVersionCode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"availableVersionCode\" is null.");
      }
      this.availableVersionCode = setterArg;
    }

    private @NonNull Long installStatus;

    public @NonNull Long getInstallStatus() {
      return installStatus;
    }

    public void setInstallStatus(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"installStatus\" is null.");
      }
      this.installStatus = setterArg;
    }

    private @NonNull String packageName;

    public @NonNull String getPackageName() {
      return packageName;
    }

    public void setPackageName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packageName\" is null.");
      }
      this.packageName = setterArg;
    }

    private @NonNull Long updateAvailability;

    public @NonNull Long getUpdateAvailability() {
      return updateAvailability;
    }

    public void setUpdateAvailability(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"updateAvailability\" is null.");
      }
      this.updateAvailability = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    UpdateInfo() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      UpdateInfo that = (UpdateInfo) o;
      return availableVersionCode.equals(that.availableVersionCode) && installStatus.equals(that.installStatus) && packageName.equals(that.packageName) && updateAvailability.equals(that.updateAvailability);
    }

    @Override
    public int hashCode() {
      return Objects.hash(availableVersionCode, installStatus, packageName, updateAvailability);
    }

    public static final class Builder {

      private @Nullable Long availableVersionCode;

      @CanIgnoreReturnValue
      public @NonNull Builder setAvailableVersionCode(@NonNull Long setterArg) {
        this.availableVersionCode = setterArg;
        return this;
      }

      private @Nullable Long installStatus;

      @CanIgnoreReturnValue
      public @NonNull Builder setInstallStatus(@NonNull Long setterArg) {
        this.installStatus = setterArg;
        return this;
      }

      private @Nullable String packageName;

      @CanIgnoreReturnValue
      public @NonNull Builder setPackageName(@NonNull String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      private @Nullable Long updateAvailability;

      @CanIgnoreReturnValue
      public @NonNull Builder setUpdateAvailability(@NonNull Long setterArg) {
        this.updateAvailability = setterArg;
        return this;
      }

      public @NonNull UpdateInfo build() {
        UpdateInfo pigeonReturn = new UpdateInfo();
        pigeonReturn.setAvailableVersionCode(availableVersionCode);
        pigeonReturn.setInstallStatus(installStatus);
        pigeonReturn.setPackageName(packageName);
        pigeonReturn.setUpdateAvailability(updateAvailability);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(availableVersionCode);
      toListResult.add(installStatus);
      toListResult.add(packageName);
      toListResult.add(updateAvailability);
      return toListResult;
    }

    static @NonNull UpdateInfo fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      UpdateInfo pigeonResult = new UpdateInfo();
      Object availableVersionCode = pigeonVar_list.get(0);
      pigeonResult.setAvailableVersionCode((Long) availableVersionCode);
      Object installStatus = pigeonVar_list.get(1);
      pigeonResult.setInstallStatus((Long) installStatus);
      Object packageName = pigeonVar_list.get(2);
      pigeonResult.setPackageName((String) packageName);
      Object updateAvailability = pigeonVar_list.get(3);
      pigeonResult.setUpdateAvailability((Long) updateAvailability);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class RequestResponse {
    private @NonNull Long bytesDownloaded;

    public @NonNull Long getBytesDownloaded() {
      return bytesDownloaded;
    }

    public void setBytesDownloaded(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"bytesDownloaded\" is null.");
      }
      this.bytesDownloaded = setterArg;
    }

    private @NonNull Long installErrorCode;

    public @NonNull Long getInstallErrorCode() {
      return installErrorCode;
    }

    public void setInstallErrorCode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"installErrorCode\" is null.");
      }
      this.installErrorCode = setterArg;
    }

    private @NonNull Long installStatus;

    public @NonNull Long getInstallStatus() {
      return installStatus;
    }

    public void setInstallStatus(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"installStatus\" is null.");
      }
      this.installStatus = setterArg;
    }

    private @NonNull String packageName;

    public @NonNull String getPackageName() {
      return packageName;
    }

    public void setPackageName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packageName\" is null.");
      }
      this.packageName = setterArg;
    }

    private @NonNull Long totalBytesToDownload;

    public @NonNull Long getTotalBytesToDownload() {
      return totalBytesToDownload;
    }

    public void setTotalBytesToDownload(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"totalBytesToDownload\" is null.");
      }
      this.totalBytesToDownload = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    RequestResponse() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      RequestResponse that = (RequestResponse) o;
      return bytesDownloaded.equals(that.bytesDownloaded) && installErrorCode.equals(that.installErrorCode) && installStatus.equals(that.installStatus) && packageName.equals(that.packageName) && totalBytesToDownload.equals(that.totalBytesToDownload);
    }

    @Override
    public int hashCode() {
      return Objects.hash(bytesDownloaded, installErrorCode, installStatus, packageName, totalBytesToDownload);
    }

    public static final class Builder {

      private @Nullable Long bytesDownloaded;

      @CanIgnoreReturnValue
      public @NonNull Builder setBytesDownloaded(@NonNull Long setterArg) {
        this.bytesDownloaded = setterArg;
        return this;
      }

      private @Nullable Long installErrorCode;

      @CanIgnoreReturnValue
      public @NonNull Builder setInstallErrorCode(@NonNull Long setterArg) {
        this.installErrorCode = setterArg;
        return this;
      }

      private @Nullable Long installStatus;

      @CanIgnoreReturnValue
      public @NonNull Builder setInstallStatus(@NonNull Long setterArg) {
        this.installStatus = setterArg;
        return this;
      }

      private @Nullable String packageName;

      @CanIgnoreReturnValue
      public @NonNull Builder setPackageName(@NonNull String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      private @Nullable Long totalBytesToDownload;

      @CanIgnoreReturnValue
      public @NonNull Builder setTotalBytesToDownload(@NonNull Long setterArg) {
        this.totalBytesToDownload = setterArg;
        return this;
      }

      public @NonNull RequestResponse build() {
        RequestResponse pigeonReturn = new RequestResponse();
        pigeonReturn.setBytesDownloaded(bytesDownloaded);
        pigeonReturn.setInstallErrorCode(installErrorCode);
        pigeonReturn.setInstallStatus(installStatus);
        pigeonReturn.setPackageName(packageName);
        pigeonReturn.setTotalBytesToDownload(totalBytesToDownload);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(5);
      toListResult.add(bytesDownloaded);
      toListResult.add(installErrorCode);
      toListResult.add(installStatus);
      toListResult.add(packageName);
      toListResult.add(totalBytesToDownload);
      return toListResult;
    }

    static @NonNull RequestResponse fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      RequestResponse pigeonResult = new RequestResponse();
      Object bytesDownloaded = pigeonVar_list.get(0);
      pigeonResult.setBytesDownloaded((Long) bytesDownloaded);
      Object installErrorCode = pigeonVar_list.get(1);
      pigeonResult.setInstallErrorCode((Long) installErrorCode);
      Object installStatus = pigeonVar_list.get(2);
      pigeonResult.setInstallStatus((Long) installStatus);
      Object packageName = pigeonVar_list.get(3);
      pigeonResult.setPackageName((String) packageName);
      Object totalBytesToDownload = pigeonVar_list.get(4);
      pigeonResult.setTotalBytesToDownload((Long) totalBytesToDownload);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DownloadResponse {
    private @NonNull Long code;

    public @NonNull Long getCode() {
      return code;
    }

    public void setCode(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"code\" is null.");
      }
      this.code = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DownloadResponse() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      DownloadResponse that = (DownloadResponse) o;
      return code.equals(that.code);
    }

    @Override
    public int hashCode() {
      return Objects.hash(code);
    }

    public static final class Builder {

      private @Nullable Long code;

      @CanIgnoreReturnValue
      public @NonNull Builder setCode(@NonNull Long setterArg) {
        this.code = setterArg;
        return this;
      }

      public @NonNull DownloadResponse build() {
        DownloadResponse pigeonReturn = new DownloadResponse();
        pigeonReturn.setCode(code);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(1);
      toListResult.add(code);
      return toListResult;
    }

    static @NonNull DownloadResponse fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      DownloadResponse pigeonResult = new DownloadResponse();
      Object code = pigeonVar_list.get(0);
      pigeonResult.setCode((Long) code);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return UpdateInfo.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return RequestResponse.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return DownloadResponse.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof UpdateInfo) {
        stream.write(129);
        writeValue(stream, ((UpdateInfo) value).toList());
      } else if (value instanceof RequestResponse) {
        stream.write(130);
        writeValue(stream, ((RequestResponse) value).toList());
      } else if (value instanceof DownloadResponse) {
        stream.write(131);
        writeValue(stream, ((DownloadResponse) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface RustoreUpdate {

    void info(@NonNull Result<UpdateInfo> result);

    void listener(@NonNull Result<RequestResponse> result);

    void immediate(@NonNull Result<DownloadResponse> result);

    void silent(@NonNull Result<DownloadResponse> result);

    void download(@NonNull Result<DownloadResponse> result);

    void completeUpdateSilent(@NonNull VoidResult result);

    void completeUpdateFlexible(@NonNull VoidResult result);

    /** The codec used by RustoreUpdate. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `RustoreUpdate` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable RustoreUpdate api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable RustoreUpdate api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_update.RustoreUpdate.info" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<UpdateInfo> resultCallback =
                    new Result<UpdateInfo>() {
                      public void success(UpdateInfo result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.info(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_update.RustoreUpdate.listener" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<RequestResponse> resultCallback =
                    new Result<RequestResponse>() {
                      public void success(RequestResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.listener(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_update.RustoreUpdate.immediate" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<DownloadResponse> resultCallback =
                    new Result<DownloadResponse>() {
                      public void success(DownloadResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.immediate(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_update.RustoreUpdate.silent" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<DownloadResponse> resultCallback =
                    new Result<DownloadResponse>() {
                      public void success(DownloadResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.silent(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_update.RustoreUpdate.download" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<DownloadResponse> resultCallback =
                    new Result<DownloadResponse>() {
                      public void success(DownloadResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.download(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_update.RustoreUpdate.completeUpdateSilent" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.completeUpdateSilent(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_rustore_update.RustoreUpdate.completeUpdateFlexible" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.completeUpdateFlexible(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
